version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Paris
    commit-message:
      prefix: ci
      prefix-development: ci
      include: scope
    groups:
      rollup:
        patterns:
          - "@rollup/*"
