extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    allow_inplace_checks: true
    merge_method: squash

merge_protections:
  - name: 🤖 Continuous Integration
    if:
      - label != hotfix
    success_conditions:
      - and: &CheckRuns
          - check-success = lint
          - check-success = test
          - or:
              - label = ignore-broken-links
              - check-success = test-broken-links
          - or:
              - check-success=Cloudflare Pages
              # fork can't have the preview build
              - "-head-repo-full-name~=^Mergifyio/"

  - name: 👀 Review Requirements
    if:
      - label != hotfix
    success_conditions:
      - or: &DefaultReviewCond
          - "#approved-reviews-by >= 2"
          - author = dependabot[bot]
          - author = mergify-ci-bot

  - name: 🧑‍🚒 Hotfix Review Requirements
    if:
      - label = hotfix
    success_conditions:
      - or: &HotfixReviewCond
          # Author is engineering manager, we allow with one review
          - and:
              - author=@eng-mgr
              - "#approved-reviews-by>=1"
          - and:
              - author=@devs
              # in any other case, we allow if approve by engineering manager
              # or anyone if it's a regular fix/revert
              - or:
                  - approved-reviews-by=@eng-mgr
                  - and:
                      - title~=^(revert|fix)
                      - "#approved-reviews-by>=1"

          - or: *DefaultReviewCond

      # yamllint disable-line rule:line-length
      - body ~= (Fix|Related).* (INC-\d+|https:\/\/github\.com\/Mergifyio\/docs\/security\/dependabot\/\d+)

queue_rules:
  - name: hotfix
    <<: *DefaultQueueOptions
    queue_conditions:
      - label = hotfix
    merge_conditions:
      - and: *CheckRuns

  - name: default
    <<: *DefaultQueueOptions
    queue_conditions:
      - and: *CheckRuns
    merge_conditions:
      - schedule=Mon-Fri 09:00-17:30[Europe/Paris]

  - name: lowprio
    <<: *DefaultQueueOptions
    merge_method: merge
    queue_conditions:
      - and: *CheckRuns
      - "#commits=1"
      - or:
          - and:
              - author=mergify-ci-bot
              - head = json-schema-types-sync
              - "title~=^chore: sync"
          - and:
              - author=mergify-ci-bot
              - head~=^clifus/
              - "title~=^chore: bump"
          - author=dependabot[bot]
    merge_conditions:
      - schedule=Mon-Fri 09:00-17:00[Europe/Paris]
    batch_size: 7
    batch_max_wait_time: 5min
    queue_branch_merge_method: fast-forward
    commit_message_template:

pull_request_rules:
  - name: automatic merge
    conditions:
      - label != manual merge
      - base=main
    actions:
      queue:

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - and: *CheckRuns
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

merge_queue:
  max_parallel_checks: 5
