extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_format:
      title: pr-title
      body: pr-body
    merge_method: squash

commands:
  defaults:
    restrictions:
      conditions: []

priority_rules:
  - name: hotfix
    priority: high
    conditions:
      - label = hotfix
    allow_checks_interruption: true

queue_rules:
  - name: default
    <<: *DefaultQueueOptions
    queue_conditions: []
    merge_conditions: []
