import type { GetStaticPathsOptions, GetStaticPathsResult } from 'astro';
import { getStaticPaths } from '../pages/open-graph/[...path]';

/**
 * astro-og-canvas 0.13 derives the route parameter name from the route pattern that
 * Astro hands to `getStaticPaths()`, so calling it from outside Astro's router means
 * passing that pattern ourselves — an empty options object throws. Keep it in sync
 * with the filename of the image endpoint imported above.
 */
const routes = (await getStaticPaths({
  routePattern: '/open-graph/[...path]',
} as GetStaticPathsOptions)) as GetStaticPathsResult;

/**  All the OpenGraph image paths as generated by our `getStaticPaths`. */
const paths = new Set(routes.map(({ params }) => params.path));

/**
 * Get the path to the OpenGraph image for a page
 * @param path Pathname of the page URL.
 * @returns Path to the OpenGraph image if found. Otherwise, `undefined`.
 */
export function getOgImageUrl(path: string): string | undefined {
  const imagePath = path.replace(/^\//, '').replace(/\/$/, '') + '.png';
  if (paths.has(imagePath)) return '/open-graph/' + imagePath;
}
